// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: idl/ywx.proto

package ywx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InId int32 `protobuf:"varint,1,opt,name=inId,proto3" json:"inId,omitempty"`
}

func (x *PidRequest) Reset() {
	*x = PidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_ywx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PidRequest) ProtoMessage() {}

func (x *PidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_ywx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PidRequest.ProtoReflect.Descriptor instead.
func (*PidRequest) Descriptor() ([]byte, []int) {
	return file_idl_ywx_proto_rawDescGZIP(), []int{0}
}

func (x *PidRequest) GetInId() int32 {
	if x != nil {
		return x.InId
	}
	return 0
}

type PidReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutId int32 `protobuf:"varint,1,opt,name=outId,proto3" json:"outId,omitempty"`
}

func (x *PidReply) Reset() {
	*x = PidReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_ywx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PidReply) ProtoMessage() {}

func (x *PidReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_ywx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PidReply.ProtoReflect.Descriptor instead.
func (*PidReply) Descriptor() ([]byte, []int) {
	return file_idl_ywx_proto_rawDescGZIP(), []int{1}
}

func (x *PidReply) GetOutId() int32 {
	if x != nil {
		return x.OutId
	}
	return 0
}

type IPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IPRequest) Reset() {
	*x = IPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_ywx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPRequest) ProtoMessage() {}

func (x *IPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_ywx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPRequest.ProtoReflect.Descriptor instead.
func (*IPRequest) Descriptor() ([]byte, []int) {
	return file_idl_ywx_proto_rawDescGZIP(), []int{2}
}

type IPReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (x *IPReply) Reset() {
	*x = IPReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_ywx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPReply) ProtoMessage() {}

func (x *IPReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_ywx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPReply.ProtoReflect.Descriptor instead.
func (*IPReply) Descriptor() ([]byte, []int) {
	return file_idl_ywx_proto_rawDescGZIP(), []int{3}
}

func (x *IPReply) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

var File_idl_ywx_proto protoreflect.FileDescriptor

var file_idl_ywx_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x64, 0x6c, 0x2f, 0x79, 0x77, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x79, 0x77, 0x78, 0x22, 0x20, 0x0a, 0x0a, 0x50, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x08, 0x50, 0x69, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x49, 0x50, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x07, 0x49, 0x50, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50,
	0x32, 0x5c, 0x0a, 0x05, 0x54, 0x65, 0x73, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x50, 0x69, 0x64, 0x12, 0x0f, 0x2e, 0x79, 0x77, 0x78, 0x2e, 0x50, 0x69, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x79, 0x77, 0x78, 0x2e, 0x50, 0x69, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x49, 0x50, 0x12, 0x0e,
	0x2e, 0x79, 0x77, 0x78, 0x2e, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c,
	0x2e, 0x79, 0x77, 0x78, 0x2e, 0x49, 0x50, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x79, 0x77, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_ywx_proto_rawDescOnce sync.Once
	file_idl_ywx_proto_rawDescData = file_idl_ywx_proto_rawDesc
)

func file_idl_ywx_proto_rawDescGZIP() []byte {
	file_idl_ywx_proto_rawDescOnce.Do(func() {
		file_idl_ywx_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_ywx_proto_rawDescData)
	})
	return file_idl_ywx_proto_rawDescData
}

var file_idl_ywx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_ywx_proto_goTypes = []interface{}{
	(*PidRequest)(nil), // 0: ywx.PidRequest
	(*PidReply)(nil),   // 1: ywx.PidReply
	(*IPRequest)(nil),  // 2: ywx.IPRequest
	(*IPReply)(nil),    // 3: ywx.IPReply
}
var file_idl_ywx_proto_depIdxs = []int32{
	0, // 0: ywx.Teser.GetPid:input_type -> ywx.PidRequest
	2, // 1: ywx.Teser.GetIP:input_type -> ywx.IPRequest
	1, // 2: ywx.Teser.GetPid:output_type -> ywx.PidReply
	3, // 3: ywx.Teser.GetIP:output_type -> ywx.IPReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_ywx_proto_init() }
func file_idl_ywx_proto_init() {
	if File_idl_ywx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_ywx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_ywx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PidReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_ywx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_ywx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_ywx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_ywx_proto_goTypes,
		DependencyIndexes: file_idl_ywx_proto_depIdxs,
		MessageInfos:      file_idl_ywx_proto_msgTypes,
	}.Build()
	File_idl_ywx_proto = out.File
	file_idl_ywx_proto_rawDesc = nil
	file_idl_ywx_proto_goTypes = nil
	file_idl_ywx_proto_depIdxs = nil
}
